# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- static_analysis
- build
- test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
  - user_service/.gradle/wrapper
  - user_service/.gradle/caches

static_analysis:
  stage: static_analysis
  image: gradle:jdk17
  script:
    - cd user_service
    - gradle spotbugsMain spotbugsTest
  artifacts:
    reports:
      codequality: user_service/app/build/reports/spotbugs/main.xml
    paths:
      - user_service/app/build/reports/spotbugs/

build:
  stage: build
  image: gradle:jdk17
  script:
  - cd user_service
  - gradle build
  artifacts:
    paths:
    - user_service/app/build/libs/*.jar
  dependencies:
  - static_analysis

test:
  stage: test
  image: gradle:jdk17
  script:
  - cd user_service
  - gradle test
  dependencies:
  - build
