# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/pipeline/#customization
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- security_testing
- build
- test

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  paths:
  - user_service/app/.gradle/wrapper
  - user_service/app/.gradle/caches

static_analysis:
  stage: security_testing
  image: gradle:jdk17
  script:
    - cd user_service
    - gradle spotbugsMain spotbugsTest
    # Check if SpotBugs found any issues
    - |
      if (Test-Path "app/build/reports/spotbugs/main.xml") {
        $xml = [xml](Get-Content "app/build/reports/spotbugs/main.xml")
        $bugCount = $xml.SelectNodes("//BugInstance").Count
        if ($bugCount -gt 0) {
          Write-Host "::warning::SpotBugs found $bugCount potential issues. Please review the detailed report in the artifacts."
          Write-Host "::warning::To view the report, download the artifacts from this job or check the Code Quality report."
          # Exit with code 0 to allow the pipeline to continue, but with a warning
          exit 0
        }
      }
  artifacts:
    reports:
      codequality: user_service/app/build/reports/spotbugs/main.xml
    paths:
      - user_service/app/build/reports/spotbugs/
  allow_failure: true  # Allow the stage to fail without stopping the pipeline

dependency_check:
  stage: security_testing
  image: gradle:jdk17
  script:
    - cd user_service
    - gradle dependencyCheckAnalyze
    # Check if dependency check found any issues
    - |
      if (Test-Path "app/build/reports/dependency-check-report.html") {
        $html = Get-Content "app/build/reports/dependency-check-report.html" -Raw
        if ($html -match "Vulnerabilities Found") {
          Write-Host "::warning::Dependency check found vulnerabilities. Please review the report in the artifacts."
          Write-Host "::warning::To view the report, download the artifacts from this job."
          # Exit with code 0 to allow the pipeline to continue, but with a warning
          exit 0
        }
      }
  artifacts:
    paths:
      - user_service/app/build/reports/dependency-check-report.html
  allow_failure: true  # Allow the stage to fail without stopping the pipeline

build:
  stage: build
  image: gradle:jdk17
  script:
  - cd user_service
  - gradle build
  artifacts:
    paths:
    - user_service/app/build/libs/*.jar
  dependencies:
  - static_analysis
  - dependency_check

test:
  stage: test
  image: gradle:jdk17
  script:
  - cd user_service
  - gradle test
  dependencies:
  - build
