env:
  contexts:
    - name: user-service-context
      urls:
        - "http://host.docker.internal:8087"
      includePaths:
        - "http://host.docker.internal:8087.*"
      authentication:
        method: script
        parameters:
          script: JWT Script-based Authentication
          scriptEngine: ECMAScript : Oracle Nashorn
          scriptFile: /zap/scripts/authenticate.js
          loginUrl: "http://host.docker.internal:8087/api/v1/auth/login"
          loginRequestBody: '{"username":"your_username","password":"your_password"}'
          tokenJsonPath: "$.token" # Adjust this to match your API's response
        verification:
          method: response
          loggedInRegex: ".*"
          loggedOutRegex: "401 Unauthorized"
      users:
        - name: zapuser
          credentials:
            username: "your_username"
            password: "your_password"
          forced: true

jobs:
  - type: spider
    parameters:
      context: user-service-context
      user: zapuser
      url: "http://host.docker.internal:8087"
      maxDuration: 2

  - type: passiveScan-wait

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/wrk
      reportFile: zap_report.html