apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: user-service
type: Opaque
data:
  db-username: <base64-encoded-db-username>
  db-password: <base64-encoded-db-password> 