apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  spring.datasource.url: ${BASE64_ENCODED_DATASOURCE_URL}
  spring.datasource.username: ${BASE64_ENCODED_DATASOURCE_USERNAME}
  spring.datasource.password: ${BASE64_ENCODED_DATASOURCE_PASSWORD}
  encryption.key: NWV2b0paenYyaUpEWm8yQXNuK1ZZaWIyKzJXTHJuTEdwTFpTSlhzMkVtQT0=