apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: libraflow
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8087
    protocol: TCP
    name: http
  selector:
    app: user-service 