apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8087
    protocol: TCP
    name: http
  selector:
    app: user-service