apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountBinding
metadata:
  name: cloudsql-binding
  namespace: user-service
spec:
  serviceAccountRef:
    name: cloudsql-sa
  roles:
    - roles/cloudsql.client
  gcpServiceAccountRef:
    name: kubernetes-deploy
    namespace: user-service